# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: campaignchain

# The type of the application to build.
type: php:7.0
build:
  flavor: symfony

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysql:mysql"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/app.php"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/app/cache": "shared:files/cache"
    "/app/logs": "shared:files/logs"
    "/app/sessions": "shared:files/sessions"
    "/app/config": "shared:files/config"

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
      echo 'imports:' >> app/config/parameters.yml
      echo '    - { resource: parameters_platformsh.php }' >> app/config/parameters.yml
      rm web/app_dev.php
      app/console --env=prod assetic:dump --no-debug
    deploy: |
      app/console --env=prod cache:clear
# The processes that are triggered on a schedule.
crons:
    campaignchain:
        spec: "*/1 * * * *"
        cmd: "cd web && php app/console campaignchain:scheduler --env=prod 1>/dev/null 2>/dev/null"