imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: campaignchain/config.yml }
    - { resource: campaignchain/config_bundles.yml }