imports:
    - { resource: parameters.yml }
    - { resource: assetic.yml }
    - { resource: config_campaignchain.yml }
    - { resource: ../campaignchain/config/imports.yml }
    - { resource: config_campaignchain_bundles.yml }
    - { resource: security.yml }