imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ["scheduler", "tracking", "external"]
    handlers:
        scheduler:
            type: rotating_file
            path: "%kernel.logs_dir%/scheduler.log"
            level: debug
            channels: [scheduler]
            max_files: 10
        tracking:
            type: rotating_file
            path: "%kernel.logs_dir%/tracking.log"
            level: debug
            channels: [tracking]
            max_files: 10
        external:
            type: rotating_file
            path: "%kernel.logs_dir%/external.log"
            level: debug
            channels: [external]
            max_files: 10
        main:
            type:         fingers_crossed
            excluded_404s:
                - ^/
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!scheduler, !event, !tracking, !external]
        console:
            type:  console