imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: config_campaignchain.yml }
    - { resource: ../campaignchain/config/bundles.yml }