# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

"http://{default}/":
    type: upstream
    # the first part should be your project name
    upstream: "campaignchain:http"